### ISSUE TITLE
⚠️🐞Critical BUG

### ISSUE THREAD

**Issue by yossefomar** [YP6/AI-Interviewer-BOT#21]
## 🐞Describe the bug
Fail to register , when sending the user credentials get this : 
{"Error 400":"Bad Request","detail":"Group matching query does not exist."}

## ⚠️ Why is it critical?
1- If user cannot register , then he can't complete the process.
2- without creating user and insert password to credentials, then we cannot type add the Hashed password to the database. 

## 🔢To Reproduce
1. Go to 'Postman'
2. Click on 'register , add credentials then send'
3. See the error

## ✅Expected behavior
return {"OK 200":"Sucess","detail":"Registered"}

## 📷Screenshots
![image.png](https://images.zenhubusercontent.com/6340ccc178f145cfe2e09488/f20ca8fd-efcd-4797-9f92-78b7a9b3b1fa)

**Comment by youssefkhaled001** [comment]
Not A Bug

**Comment by youssefkhaled001** [comment]
Not A Bug
