### ISSUE TITLE
⚠️🐞user can login without account type

### ISSUE THREAD

**Issue by YoussefMaged2001** [YP6/AI-Interviewer-BOT#27]
## 🐞Describe the bug
user can register without selecting account type 

## ⚠️ Why is it critical?
every user should have a type in order to be assigned appropriate roles

## 🔢To Reproduce
1. Go to 'register'
2. fill user details without selecting an account type 
3. click submit it will register the account 

## ✅Expected behavior
it should reject if the user did not select an account type

**Comment by youssefeid019** [comment]
Fixed
