### ISSUE TITLE
🐞can choose dates from future

### ISSUE THREAD

**Issue by YoussefMaged2001** [YP6/AI-Interviewer-BOT#28]
## 🐞Describe the bug
in the register there is nothing that indicates that the date field is for the birthdate and also i can choose  date from the future or any recent date which is not applicable

## 🔢To Reproduce
1. Go to 'register'
2. Click on the date field and choose any date from the future 
3. press submit and it will accept the date 

## ✅Expected behavior
there should be an age limit at least 18yo

**Comment by youssefeid019** [comment]
Fixed
